name: daily-automatic-update
on:
  schedule:
    - cron: "0 17 * * *"
  workflow_dispatch:

env:
  Username: ${{ secrets.Username }}
  Token: ${{ secrets.Token }}
  Name: ${{ secrets.Name }}
  Email: ${{ secrets.EMAIL }}

jobs:

  daily-automatic-update:
    runs-on: ubuntu-latest
  
    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET 7.0
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x

      - name: Install dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Run
        run: dotnet run --project src/Soenneker.Data.ZipCode.csproj --no-restore --verbosity normal --framework net7.0